apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-server.fullname" . }}
  labels:
    {{- include "grpc-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "grpc-server.selectorLabels" . | nindent 4 }}
